### ISSUE TITLE
Blob viz minor bugs

### ISSUE THREAD

**Issue by enoriega** [enoriega/frailty_graph_viz#32]
@rahatzamancse : 

- The Cells and tissues shows one entity less than the number configured on the entity panel. (i.e. 4 instead of 5)
- Edge opacity isn't restored after coming back from the edge view
- When opened, the viz is sloppy, is this something easy to fix?

**Comment by rahatzamancse** [comment]
@enoriega,

I fixed the first two bugs. About the third one, I need to do more investigation and optimization.

**Comment by enoriega** [comment]
@rahatzamancse Can you create a pull request with the first two fixes?
Thanks!

**Comment by enoriega** [comment]
@rahatzamancse Only this bug remains outstanding:

![image](https://user-images.githubusercontent.com/4502559/175752061-b81bca08-a683-4583-8345-a881e6650f2b.png)

The cells and tissue blob shows three instead of five elements in this specific instance of blob viz
